// Embed the web assets as importable strings so the Session Host never reads them from disk.
// That keeps a single-executable build (M5) unblocked, and it is why src/web/assets.generated.ts
// is committed. `npm run build:assets` regenerates it; a test fails if it drifts.
import { readFileSync, writeFileSync } from "node:fs";
import { stripTypeScriptTypes } from "node:module";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");

export function buildAssets() {
  const read = (path) => readFileSync(join(root, path), "utf8");

  // The browser runs the same reducer as the TUI. reduce.ts imports only types, so stripping
  // leaves standalone ESM with no imports — no bundler, and no second copy to drift.
  const browserModule = (path) => {
    const stripped = stripTypeScriptTypes(read(path), { mode: "strip" });
    if (/^\s*import\s+[^t]/m.test(stripped)) {
      throw new Error(`${path} gained a value import; it can no longer be served to the browser as-is`);
    }
    return stripped;
  };
  const reducer = browserModule("src/client/reduce.ts");
  const diff = browserModule("src/client/diff.ts");

  const literal = (value) => JSON.stringify(value);
  return [
    "// Generated by scripts/build-assets.mjs. Do not edit; run `npm run build:assets`.",
    "",
    `export const INDEX_HTML = ${literal(read("src/web/index.html"))};`,
    "",
    `export const STYLES_CSS = ${literal(read("src/web/styles.css"))};`,
    "",
    `export const APP_JS = ${literal(read("src/web/app.js"))};`,
    "",
    `export const REDUCER_JS = ${literal(reducer)};`,
    "",
    `export const DIFF_JS = ${literal(diff)};`,
    "",
  ].join("\n");
}

if (import.meta.url === `file://${process.argv[1]}`) {
  writeFileSync(join(root, "src/web/assets.generated.ts"), buildAssets());
  console.log("wrote src/web/assets.generated.ts");
}
