// Embed Vite's build output as importable strings so the Session Host never reads assets from disk.
// That keeps a single-executable build (M5) unblocked, and it is why src/web/assets.generated.ts is
// committed. `npm run build:assets` regenerates it, via scripts/build-web.mjs, which runs Vite first.
//
// This half stays synchronous on purpose: sourceHash() is the staleness gate `npm test` relies on,
// and it has to work on a fresh clone with no web/dist and under --omit=dev with no Vite installed.
import { createHash } from "node:crypto";
import { readFileSync, readdirSync, statSync } from "node:fs";
import { dirname, extname, join, posix, sep } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const dist = join(root, "web/dist");

/**
 * Everything that can change what Vite emits. `node_modules/**` is excluded because
 * package-lock.json is its fingerprint; including the lockfile is a deliberate trade — a React bump
 * that silently shipped a bundle built against the old version would be a false negative exactly
 * where nobody would look, so take the loud failure instead. Tailwind gets no entry of its own: v4
 * has no config file, and its theme lives in a stylesheet under `web` like any other.
 */
const HASH_INPUTS = ["web", "src/client", "src/protocol", "package.json", "package-lock.json"];
const NEVER_HASHED = new Set(["dist", "node_modules"]);

const CONTENT_TYPES = {
  ".css": ["text/css", true],
  ".html": ["text/html", true],
  ".ico": ["image/x-icon", false],
  ".js": ["text/javascript", true],
  ".json": ["application/json", true],
  ".png": ["image/png", false],
  ".svg": ["image/svg+xml", true],
  ".webp": ["image/webp", false],
  ".woff2": ["font/woff2", false],
};

// Vite names its content-hashed output `index-BQ4tYcqn.js`. Matching the hash rather than the
// assetsDir prefix means the decision survives someone changing assetsDir, and it keeps the
// judgement here — where the hashing is known — rather than in the Session Host.
const CONTENT_HASHED = /-[A-Za-z0-9_-]{8}\.[^.]+$/;

/** The embedded manifest module. `sharedModules` is recorded so a test can hold build-web.mjs to it. */
export function buildAssets(sharedModules) {
  if (!statSync(dist, { throwIfNoEntry: false })?.isDirectory()) {
    throw new Error(`no Vite output at ${dist}; run scripts/build-web.mjs, which builds it first`);
  }

  const assets = walk(dist).sort().map((relPath) => {
    const [type, isText] = CONTENT_TYPES[extname(relPath)] ?? ["application/octet-stream", false];
    const bytes = readFileSync(join(dist, relPath.split("/").join(sep)));
    return [
      `/${relPath}`,
      {
        type: isText ? `${type}; charset=utf-8` : type,
        body: isText ? bytes.toString("utf8") : bytes.toString("base64"),
        encoding: isText ? "utf8" : "base64",
        immutable: CONTENT_HASHED.test(posix.basename(relPath)),
      },
    ];
  });

  if (!assets.some(([path]) => path === "/index.html")) {
    throw new Error(`no index.html under ${dist}; run scripts/build-web.mjs rather than this file`);
  }

  const literal = (value) => JSON.stringify(value);
  return [
    "// Generated by scripts/build-web.mjs. Do not edit; run `npm run build:assets`.",
    'import type { AssetManifest } from "./assets.ts";',
    "",
    "export const ASSETS: AssetManifest = {",
    ...assets.map(([path, asset]) =>
      [
        `  ${literal(path)}: {`,
        `    type: ${literal(asset.type)},`,
        `    encoding: ${literal(asset.encoding)},`,
        `    immutable: ${asset.immutable},`,
        `    body: ${literal(asset.body)},`,
        "  },",
      ].join("\n"),
    ),
    "};",
    "",
    "/** sha256 over every input to the build above. test/web.test.ts recomputes it. */",
    `export const SOURCE_HASH = ${literal(sourceHash())};`,
    "",
    "/** What scripts/build-web.mjs proved the bundle contains, so a test can notice if it stops. */",
    `export const SHARED_MODULES: readonly string[] = ${literal([...sharedModules])};`,
    "",
  ].join("\n");
}

/**
 * A digest of the sources the committed manifest was built from. Paths are in the digest as well as
 * contents, sorted, because readdirSync order is not guaranteed and because without paths a
 * Button.tsx -> button.tsx rename would be invisible.
 */
export function sourceHash() {
  const hash = createHash("sha256");
  const files = HASH_INPUTS.flatMap((input) =>
    walk(join(root, input), NEVER_HASHED).map((relPath) => posix.join(input, relPath)),
  );

  for (const relPath of files.sort()) {
    // latin1 round-trips any byte, so this hashes the raw contents with CRLF collapsed to LF. A
    // checkout with Windows line endings must hash identically to a LF one, or a clean tree fails
    // telling you to rebuild — which would not help. .gitattributes pins eol=lf; this is the belt.
    const contents = readFileSync(join(root, relPath.split("/").join(sep))).toString("latin1");
    hash.update(relPath, "utf8");
    hash.update("\0");
    hash.update(contents.replaceAll("\r\n", "\n"), "latin1");
    hash.update("\0");
  }
  return hash.digest("hex");
}

/** Every file at or under `target`, as `/`-separated paths relative to it. A plain file yields "". */
function walk(target, excluded = new Set()) {
  const stat = statSync(target, { throwIfNoEntry: false });
  if (!stat) throw new Error(`${target} is in the hash's input set but does not exist`);
  if (!stat.isDirectory()) return [""];

  const found = [];
  const descend = (directory, prefix) => {
    for (const entry of readdirSync(directory, { withFileTypes: true })) {
      if (excluded.has(entry.name)) continue;
      if (entry.isDirectory()) descend(join(directory, entry.name), `${prefix}${entry.name}/`);
      else found.push(`${prefix}${entry.name}`);
    }
  };
  descend(target, "");
  return found;
}
